// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/pulver.h"
#include <Rcpp.h>

using namespace Rcpp;

// compute_and_save_results
DataFrame compute_and_save_results(NumericMatrix ymat, SEXP xmat_, SEXP zmat_, double rvalue_threshold, CharacterVector names, int cores, int suppress_return, int swap_x_and_z, SEXP xpstorage, SEXP xp);
RcppExport SEXP _pulver_compute_and_save_results(SEXP ymatSEXP, SEXP xmat_SEXP, SEXP zmat_SEXP, SEXP rvalue_thresholdSEXP, SEXP namesSEXP, SEXP coresSEXP, SEXP suppress_returnSEXP, SEXP swap_x_and_zSEXP, SEXP xpstorageSEXP, SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xmat_(xmat_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type zmat_(zmat_SEXP);
    Rcpp::traits::input_parameter< double >::type rvalue_threshold(rvalue_thresholdSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type suppress_return(suppress_returnSEXP);
    Rcpp::traits::input_parameter< int >::type swap_x_and_z(swap_x_and_zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xpstorage(xpstorageSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_and_save_results(ymat, xmat_, zmat_, rvalue_threshold, names, cores, suppress_return, swap_x_and_z, xpstorage, xp));
    return rcpp_result_gen;
END_RCPP
}
// write_header
void write_header(SEXP xp, CharacterVector names);
RcppExport SEXP _pulver_write_header(SEXP xpSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    write_header(xp, names);
    return R_NilValue;
END_RCPP
}
// open_output_file
SEXP open_output_file(CharacterVector filename);
RcppExport SEXP _pulver_open_output_file(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(open_output_file(filename));
    return rcpp_result_gen;
END_RCPP
}
// close_output_file
void close_output_file(SEXP xp);
RcppExport SEXP _pulver_close_output_file(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    close_output_file(xp);
    return R_NilValue;
END_RCPP
}
// create_fake_pointer
SEXP create_fake_pointer();
RcppExport SEXP _pulver_create_fake_pointer() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(create_fake_pointer());
    return rcpp_result_gen;
END_RCPP
}
// combine_results
DataFrame combine_results(List results);
RcppExport SEXP _pulver_combine_results(SEXP resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type results(resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_results(results));
    return rcpp_result_gen;
END_RCPP
}
// create_storage
XPtr<Storage> create_storage(int size, int nrow, int cores);
RcppExport SEXP _pulver_create_storage(SEXP sizeSEXP, SEXP nrowSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(create_storage(size, nrow, cores));
    return rcpp_result_gen;
END_RCPP
}
// delete_storage
void delete_storage(SEXP xp);
RcppExport SEXP _pulver_delete_storage(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    delete_storage(xp);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pulver_compute_and_save_results", (DL_FUNC) &_pulver_compute_and_save_results, 10},
    {"_pulver_write_header", (DL_FUNC) &_pulver_write_header, 2},
    {"_pulver_open_output_file", (DL_FUNC) &_pulver_open_output_file, 1},
    {"_pulver_close_output_file", (DL_FUNC) &_pulver_close_output_file, 1},
    {"_pulver_create_fake_pointer", (DL_FUNC) &_pulver_create_fake_pointer, 0},
    {"_pulver_combine_results", (DL_FUNC) &_pulver_combine_results, 1},
    {"_pulver_create_storage", (DL_FUNC) &_pulver_create_storage, 3},
    {"_pulver_delete_storage", (DL_FUNC) &_pulver_delete_storage, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pulver(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
